-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 22, 2021 at 10:54 PM
-- Server version: 10.4.6-MariaDB
-- PHP Version: 7.3.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `webscrap`
--

-- --------------------------------------------------------

--
-- Table structure for table `articles`
--

CREATE TABLE `articles` (
  `id` int(11) NOT NULL,
  `website_id` int(11) NOT NULL,
  `title` varchar(100) NOT NULL,
  `descriptionz` varchar(10000) NOT NULL,
  `dom` varchar(100) NOT NULL,
  `created_ata` timestamp NOT NULL DEFAULT current_timestamp(),
  `link` varchar(10000) NOT NULL,
  `website_name` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `articles`
--

INSERT INTO `articles` (`id`, `website_id`, `title`, `descriptionz`, `dom`, `created_ata`, `link`, `website_name`) VALUES
(233, 1, 'Ø´Ø±Ø­ Ø¹Ù…Ù„Ø© Ø§Ù„Ø¨ÙŠØªÙƒÙˆÙŠÙ† : Ø£ÙØ¶Ù„ Ø·Ø±Ù‚ Ø´Ø±Ø­ Ø¹Ù…Ù„Ø© Ø§Ù„Ø¨ÙŠØªÙƒÙˆÙŠÙ†', 'Ù„ÙŠØ³ Ù‡Ù†Ø§Ùƒ Ø´Ùƒ ÙÙŠ Ø£Ù† Ø´Ø±Ø­ Ø¹Ù…Ù„Ø© Ø§Ù„Ø¨ÙŠØªÙƒÙˆÙŠÙ† Ù…ÙˆØ¶ÙˆØ¹ Ù‡Ø§Ù… . ÙØ¨Ø§Ù„ÙƒØ§Ø¯ Ù„Ø§ÙŠÙˆØ¬Ø¯ ÙŠÙˆÙ… ÙŠÙ…Ø± Ø¯ÙˆÙ† Ø£Ø®Ø¨Ø§Ø± Ø¹Ù† Ø§Ù„Ø¨ÙŠØªÙƒÙˆÙŠÙ†ØŒ Ø®Ø§ØµØ©&hellip;', 'div[class=\"post-details\"]', '2021-05-01 01:06:46', 'https://www.mklat.com/%d8%b4%d8%b1%d8%ad-%d8%b9%d9%85%d9%84%d8%a9-%d8%a7%d9%84%d8%a8%d9%8a%d8%aa%d9%83%d9%88%d9%8a%d9%86/', 'mklat'),
(234, 1, 'Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø¥ØµØ·Ù†Ø§Ø¹ÙŠ &#8211; Ù…Ø§ Ù‡Ùˆ Ùˆ ÙƒÙŠÙ ÙŠØ¹Ù…Ù„ Ùˆ Ù…Ø§ Ø§Ø³ØªØ®Ø¯Ø§Ù…Ø§Øª Ø§Ù„', 'Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø¥ØµØ·Ù†Ø§Ø¹ÙŠ, ÙØ±Ø¹ ÙˆØ§Ø³Ø¹ Ø§Ù„Ù†Ø·Ø§Ù‚ Ù…Ù† ÙØ±ÙˆØ¹ Ø¹Ù„ÙˆÙ… Ø§Ù„ÙƒÙ…Ø¨ÙŠÙˆØªØ± ÙŠÙ‡ØªÙ… Ø¨Ø¨Ù†Ø§Ø¡ Ø¢Ù„Ø§Øª Ø°ÙƒÙŠØ© Ù‚Ø§Ø¯Ø±Ø© Ø¹Ù„Ù‰ Ø£Ø¯Ø§Ø¡ Ù…Ù‡Ø§Ù… ØªØªØ·Ù„Ø¨ Ø¹Ø§Ø¯Ø© Ø°ÙƒØ§Ø¡Ù‹&hellip;', 'div[class=\"post-details\"]', '2021-05-01 01:06:46', 'https://www.mklat.com/%d8%a7%d8%b3%d8%aa%d8%ae%d8%af%d8%a7%d9%85%d8%a7%d8%aa-%d8%a7%d9%84%d8%b0%d9%83%d8%a7%d8%a1-%d8%a7%d9%84%d8%a5%d8%b5%d8%b7%d9%86%d8%a7%d8%b9%d9%8a/', 'mklat'),
(235, 1, 'Ù…Ø§ Ù‡ÙŠ Ø§Ù„Ø±ÙˆØ¨ÙˆØª ØµÙˆÙÙŠØ§ Ù…Ø¹Ø¬Ø²Ø© Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠ ÙˆÙ…Ø§ Ù‡ÙŠ Ø£Ø´Ù‡Ø± ', 'Ø¥Ù† ÙƒÙ†Øª Ù…Ø¯Ø®Ù†Ø§ ÙˆØ­Ø§Ù„ÙÙƒ Ø§Ù„Ø­Ø¸ Ù„Ù…Ù‚Ø§Ø¨Ù„Ø© Ø§Ù„Ø±ÙˆØ¨ÙˆØª ØµÙˆÙÙŠØ§ ÙØ¨Ø§Ù„ØªØ£ÙƒÙŠØ¯ Ø³ØªØ·Ù„Ø¨ Ù…Ù†Ùƒ Ø¹Ù„Ù‰ Ø§Ù„ÙÙˆØ± Ø£Ù† ØªØªÙˆÙ‚Ù Ø¹Ù† ØªÙ„Ùƒ Ø§Ù„Ø³ÙŠØ¬Ø§Ø±Ø© Ø§Ù„Ù„Ø¹ÙŠÙ†Ø© Ù„Ø£Ù†Ù‡Ø§&hellip;', 'div[class=\"post-details\"]', '2021-05-01 01:06:46', 'https://www.mklat.com/%d8%a7%d9%84%d8%b1%d9%88%d8%a8%d9%88%d8%aa-%d8%b5%d9%88%d9%81%d9%8a%d8%a7-%d9%85%d8%b9%d8%ac%d8%b2%d8%a9-%d8%a7%d9%84%d8%b0%d9%83%d8%a7%d8%a1-%d8%a7%d9%84%d8%a7%d8%b5%d8%b7%d9%86%d8%a7%d8%b9%d9%8a/', 'mklat'),
(236, 1, 'Ù…Ø§ Ù‡ÙŠ Ø¸Ø§Ù‡Ø±Ø© Ø§Ù„Ù€FOMO ØŸ', 'Ø¸Ù‡Ø±Øª ÙÙŠ Ø§Ù„Ø¢ÙˆÙ†Ø© Ø§Ù„Ø£Ø®ÙŠØ±Ø© Ø§Ù„Ø¹Ø¯ÙŠØ¯ Ù…Ù† Ø§Ù„Ù…Ù†Ø­Ù†ÙŠØ§Øª Ø§Ù„ØªÙŠ Ø§Ù†ØªÙ‚Ù„Øª Ø¨Ù…Ø±Ø­Ù„Ø© \"Ø¥Ø¯Ù…Ø§Ù† Ø§Ù„Ø¥Ù†ØªØ±Ù†Øª\". ÙˆÙ„Ø¹Ù„ Ø£Ø¨Ø±Ø² Ù‡Ø°Ù‡ Ø§Ù„Ù…Ù†Ø­Ù†ÙŠØ§ØªØŒ Ù…Ø§ Ù‚Ø§Ù… Ø§Ù„Ù…Ø®ØªØµÙˆÙ† ÙÙŠ&hellip;', 'div[class=\"post-details\"]', '2021-05-01 01:06:46', 'https://www.mklat.com/%d9%85%d8%a7-%d9%87%d9%8a-%d8%b8%d8%a7%d9%87%d8%b1%d8%a9-%d8%a7%d9%84%d9%80fomo-%d8%9f/', 'mklat'),
(237, 1, 'Ø§Ù„Ø¢Ø«Ø§Ø± Ø§Ù„Ø¥ÙŠØ¬Ø§Ø¨ÙŠØ© Ù„Ù„Ø¥Ù†ØªØ±Ù†Øª', 'Ù‡Ù†Ø§Ùƒ ÙØ±ÙŠÙ‚ ÙŠØ±Ù‰ Ø§Ù„Ø¢Ø«Ø§Ø± Ø§Ù„Ø¥ÙŠØ¬Ø§Ø¨ÙŠØ© Ù„Ù„Ø¥Ù†ØªØ±Ù†Øª ØªØªÙ…Ø«Ù„ ÙÙ‰ Ø§Ø³ØªØ®Ø¯Ø§Ù…Ù‡ ÙÙ‰ Ø§Ù„ØªØ¹Ù„ÙŠÙ… ÙˆØ§Ù„Ø¨Ø­Ø« Ø§Ù„Ø¹Ù„Ù…Ù‰ ÙˆØ§Ù„ØªØ¬Ø§Ø±Ù‡ Ø§Ù„Ø§Ù„ÙƒØªØ±ÙˆÙ†ÙŠÙ‡ ÙˆØºÙŠØ±Ù‡Ø§ Ù…Ù† Ø§Ù„Ø§Ø«Ø§Ø± Ø§Ù„Ø§ÙŠØ¬Ø§Ø¨ÙŠÙ‡&#8230; Ø§Ù„ØªØ¹Ù„ÙŠÙ…&hellip;', 'div[class=\"post-details\"]', '2021-05-01 01:06:46', 'https://www.mklat.com/positive-effect-of-internet/', 'mklat'),
(238, 1, 'Ø®Ø·Ø± Ø¬Ø¯ÙŠØ¯ ÙŠÙ‡Ø¯Ø¯ Ø£Ù…Ù† Ø§Ù„Ø§Ù†ØªØ±Ù†Øª', 'Â Ø­Ø¯Ø¯Øª Ø§Ù„Ø¨Ø­ÙˆØ« Ø§Ù„ØªÙŠ Ø£Ø¬Ø±ÙŠØª Ù…Ø¤Ø®Ø±Ø§ ÙÙŠ Ø¬Ø§Ù…Ø¹Ø© Ø³ÙƒÙˆÙ†Ø«ÙˆØ±Ø¨ ÙÙŠ Ø§Ù„Ù…Ù…Ù„ÙƒØ© Ø§Ù„Ø¨Ø±ÙŠØ·Ø§Ù†ÙŠØ©Â Ø§Ù„Ù…ØªØ­Ø¯Ø© Ø§Ù„Ù…Ø³Ø£Ù„Ø© Ø§Ù„ØªÙ‰ ÙŠÙ…ÙƒÙ† Ø£Ù† ØªÙ…Ø«Ù„ Ø®Ø·Ø± Ø¬Ø¯ÙŠØ¯ ÙŠÙ‡Ø¯Ø¯ Ø£Ù…Ù†&hellip;', 'div[class=\"post-details\"]', '2021-05-01 01:06:46', 'https://www.mklat.com/internet-risk/', 'mklat'),
(239, 1, 'Ù…ÙŠØ²Ø© Ø¬Ø¯ÙŠØ¯Ø© Ù…Ù† Ø£Ù†Ø³ØªØºØ±Ø§Ù… Ø³ØªØ·Ù„Ø¨ Ù…Ù†Ùƒ Ø£Ù† ØªØ¹ÙŠØ¯ Ø§Ù„ØªÙÙƒÙŠØ± ÙÙŠ Ù†Ø´Ø±', 'Ù‚Ø§Ù… ØªØ·Ø¨ÙŠÙ‚ Ø£Ù†Ø³ØªØºØ±Ø§Ù… Ù…Ø¤Ø®Ø±Ø§ Ø¨Ø·Ø±Ø­ Ù…ÙŠØ²Ø© Ø¬Ø¯ÙŠØ¯Ø© Ùˆ Ù…ÙÙŠØ¯Ø© Ø­Ù‚Ø§ Ù„Ø£ÙˆÙ„ Ù…Ø±Ø©, Ø­ÙŠØ« Ø³ØªÙ‚ÙˆÙ… Ù‡Ø°Ù‡ Ø§Ù„Ù…ÙŠØ²Ø© Ø¨Ø§Ù„Ø·Ù„Ø¨ Ù…Ù† Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…ÙŠÙ† Ø§Ù„ØªÙÙƒÙŠØ±&hellip;', 'div[class=\"post-details\"]', '2021-05-01 01:06:46', 'https://www.mklat.com/instagram-new-feature/', 'mklat'),
(240, 1, 'Ù…ÙˆÙ‚Ø¹ ØªÙˆÙŠØªØ± ÙŠØ¹Ù„Ù† Ø¹Ù† Ø³ÙŠØ§Ø³Ø§Øª Ø¬Ø¯ÙŠØ¯Ø© ØªØ­Ù…ÙŠ Ø§Ù„Ù…Ø¬Ù…ÙˆØ¹Ø§Øª Ø§Ù„Ø¯ÙŠÙ†ÙŠØ©', 'Ø¥Ø°Ø§ ÙƒÙ†Øª ØªÙ‚Ø¶ÙŠ Ø£ÙŠ ÙˆÙ‚Øª Ø°ÙŠ Ù…Ø¹Ù†Ù‰ Ø¹Ù„Ù‰ Ø§Ù„Ø´Ø¨ÙƒØ© Ø§Ù„Ø§Ø¬ØªÙ…Ø§Ø¹ÙŠØ© Ø£Ùˆ Ø£Ø¯Ø®Ù„Øª ÙƒÙ„Ù…Ø§Øª Ø§Ø®ØªÙŠØ§Ø± Ù‚Ù„ÙŠÙ„Ø© ÙÙŠ Ø´Ø±ÙŠØ· Ø§Ù„Ø¨Ø­Ø« Ø§Ù„Ø®Ø§Øµ Ø¨Ù‡Ø§&hellip;', 'div[class=\"post-details\"]', '2021-05-01 01:06:46', 'https://www.mklat.com/twitter-announces-new-terms/', 'mklat'),
(241, 1, 'Ø£ÙØ¶Ù„ Ø§Ù„Ø·Ø±Ù‚ Ù„Ø¨Ù†Ø§Ø¡ ØªØ±Ø§ÙÙŠÙƒ Ù‚ÙˆÙŠ ÙˆÙ…Ø³ØªÙ‡Ø¯Ù Ù„Ù…ÙˆÙ‚Ø¹Ùƒ Ù…Ø¬Ø§Ù†Ø§ 2019', 'Ø£Ù‡Ù„Ø§ Ø¹Ø²ÙŠØ²ÙŠ , Ø­Ø§ÙˆÙ„ Ø£Ù† ØªØ³Ø£Ù„ Ø£ÙŠ ØµØ§Ø­Ø¨ Ù…ÙˆÙ‚Ø¹ Ø£Ùˆ Ù…Ø³ÙˆÙ‚ Ø§Ù„ÙƒØªØ±ÙˆÙ†ÙŠ Ø¹Ù† Ù…Ø§ ÙŠÙØ¶Ù„ÙˆÙ†Ù‡ Ùˆ Ø³ØªØ³Ù…Ø¹ Ø§Ù„Ø¬Ù…Ù„Ø© Ø§Ù„Ø´Ù‡ÙŠØ±Ø© &#8220;Ø£Ø±ÙŠØ¯&hellip;', 'div[class=\"post-details\"]', '2021-05-01 01:06:46', 'https://www.mklat.com/best-ways-build-website-traffic-2019/', 'mklat'),
(242, 1, '35 Ø®Ø·Ø£ Ù‚Ø§ØªÙ„ ÙŠÙ…ÙƒÙ† Ø§Ù† ÙŠØ¯Ù…Ø± Ù…ÙˆÙ‚Ø¹Ùƒ Ø§Ù„Ø®Ø§Øµ', '35 Ø®Ø·Ø£ Ù‚Ø§ØªÙ„ ÙŠÙ…ÙƒÙ† Ø§Ù† ÙŠØ¯Ù…Ø± Ù…ÙˆÙ‚Ø¹Ùƒ Ø§Ù„Ø®Ø§Øµ Ù‚Ø§Ù„Øª Ù…Ø­Ø±Ø±Øª Ù…ÙˆØ§Ù‚Ø¹ Ø´Ù‡ÙŠØ±Ø© Ø§Ù†Ø§ Ø¬ÙˆÙ† Ø³ÙˆÙŠÙ„ Ø®Ù„Ø§Ù„ ÙØ­ØµÙ‰ Ù„Ø§Ù„Ø§Ù Ø§Ù„Ù…ÙˆØ§Ù‚Ø¹ Ø§Ù„Ø§Ù„ÙƒØªØ±ÙˆÙ†ÙŠÙ‡&hellip;', 'div[class=\"post-details\"]', '2021-05-01 01:06:46', 'https://www.mklat.com/35-ways-to-destroy-own-website/', 'mklat'),
(243, 1, 'ØªÙ†Ø¸ÙŠÙ Ø§Ù„ÙƒÙŠØ¨ÙˆØ±Ø¯ ÙÙŠ Ø£Ø¬Ù‡Ø²Ø© Ø§Ù„Ù„Ø§Ø¨ØªÙˆØ¨', 'Ø§Ù„ØºØ¨Ø§Ø± ÙˆØ§Ù„Ø£ÙˆØ³Ø§Ø® Ø¹Ù„Ù‰ Ù„ÙˆØ­Ø© Ù…ÙØ§ØªÙŠØ­ Ø§Ù„ÙƒÙ…Ø¨ÙŠÙˆØªØ± Ø§Ù„Ù…Ø­Ù…ÙˆÙ„ ØªÙ…Ø«Ù„ Ø¹Ø§Ø¦Ù‚ Ø¹Ù†Ø¯ Ø§Ù„ÙƒØ«ÙŠØ±ÙŠÙ† ØŒ Ø®ØµÙˆØµØ§Ù‹ Ù…Ù† Ù„Ø§ ÙŠØ¹Ø±ÙÙˆÙ† ÙƒÙŠÙÙŠØ© ØªÙ†Ø¸ÙŠÙÙ‡Ø§ Ø¨ØµÙˆØ±Ø© ØµØ­ÙŠØ­Ø©&hellip;', 'div[class=\"post-details\"]', '2021-05-01 01:06:46', 'https://www.mklat.com/%d8%aa%d9%86%d8%b8%d9%8a%d9%81-%d8%a7%d9%84%d9%83%d9%8a%d8%a8%d9%88%d8%b1%d8%af-%d9%81%d9%8a-%d8%a3%d8%ac%d9%87%d8%b2%d8%a9-%d8%a7%d9%84%d9%84%d8%a7%d8%a8%d8%aa%d9%88%d8%a8/', 'mklat'),
(244, 1, 'Ø­Ø§ÙØ¸ Ø¹Ù„Ù‰ Ø´Ø­Ù† Ø¨Ø·Ø§Ø±ÙŠØ© Ø§Ù„Ù„Ø§Ø¨ØªÙˆØ¨ Ù…Ø¯Ø© Ø·ÙˆÙŠÙ„Ø©', 'Ù…Ù‚Ø¯Ù…Ø© Ø¹Ù† Ø§Ù„Ù…ÙˆØ¶ÙˆØ¹ ÙŠÙˆØ§Ø¬Ù‡ Ø§Ù„ÙƒØ«ÙŠØ±ÙŠÙ† Ù‡Ø°Ù‡ Ø§Ù„Ù…Ø´ÙƒÙ„Ø© Ø¹Ù†Ø¯ Ø§Ø³ØªØ®Ø¯Ø§Ù… Ø£Ø¬Ù‡Ø²Ø© Ø§Ù„ÙƒÙ…Ø¨ÙŠÙˆØªØ± Ø§Ù„Ù…Ø­Ù…ÙˆÙ„ ØŒ Ø®ØµÙˆØµØ§Ù‹ Ø¹Ù†Ø¯ Ø§Ø³ØªØ®Ø¯Ø§Ù…Ù‡Ø§ Ø®Ø§Ø±Ø¬ Ø§Ù„Ù…Ù†Ø²Ù„ Ø­ÙŠØ« ØªÙ†ÙØ°&hellip;', 'div[class=\"post-details\"]', '2021-05-01 01:06:46', 'https://www.mklat.com/%d8%a7%d9%84%d8%ad%d9%81%d8%a7%d8%b8-%d8%b9%d9%84%d9%8a-%d8%a8%d8%b7%d8%a7%d8%b1%d9%8a%d8%a9-%d8%a7%d9%84%d9%84%d8%a7%d8%a8%d8%aa%d9%88%d8%a8/', 'mklat'),
(245, 1, 'Ø§Ù„Ù†Ø³Ø® Ø§Ù„Ø¥Ø­ØªÙŠØ§Ø·ÙŠ Ù„Ù„Ù…Ù„ÙØ§Øª Ø¹Ù„Ù‰ Ø£Ø¬Ù‡Ø²Ø© Ø§Ù„ÙƒÙˆÙ…Ø¨ÙŠÙˆØªØ±', 'Â  Ø§Ù„Ù†Ø³Ø® Ø§Ù„Ø§Ø­ØªÙŠØ§Ø·ÙŠ Ù„Ù„Ù…Ù„ÙØ§Øª Ø¹Ù„Ù‰ Ø¬Ù‡Ø§Ø² Ø§Ù„ÙƒÙ…Ø¨ÙŠÙˆØªØ± Ø§Ù„Ù…Ø­Ù…ÙˆÙ„ Ø£Ù…Ø± Ù…Ù‡Ù… Ø¬Ø¯Ø§Ù‹ ØŒ ÙˆØ³ÙŠÙÙŠØ¯Ùƒ ÙÙŠ Ø­Ø§Ù„Ø© ÙØ´Ù„ Ø§Ù„Ù‚Ø±Øµ Ø§Ù„ØµÙ„Ø¨ Ø£Ùˆ ÙÙ‚Ø¯Ø§Ù†&hellip;', 'div[class=\"post-details\"]', '2021-05-01 01:06:46', 'https://www.mklat.com/%d8%a7%d9%84%d9%86%d8%b3%d8%ae-%d8%a7%d9%84%d8%a5%d8%ad%d8%aa%d9%8a%d8%a7%d8%b7%d9%8a-%d9%84%d9%84%d9%85%d9%84%d9%81%d8%a7%d8%aa-%d8%b9%d9%84%d9%89-%d8%a3%d8%ac%d9%87%d8%b2%d8%a9-%d8%a7%d9%84%d9%83/', 'mklat'),
(246, 1, 'ÙƒÙŠÙ ØªØ²ÙŠØ¯ Ù…Ù† Ø´Ø¹Ø¨ÙŠØªÙƒ Ø¹Ù„ÙŠ Ù…ÙˆÙ‚Ø¹ ØªÙˆÙŠØªØ± ØŸ', 'Ù…Ù† Ø§Ù„Ø·Ø±ÙŠÙ Ø£Ù† Ù†Ù‚Ø±Ø£ Ù…Ù‚ÙˆÙ„Ø© &#8221; Ù‡Ù†Ø§Ùƒ Ù†ÙˆØ¹Ø§Ù† Ù…Ù† Ø§Ù„Ø£Ø´Ø®Ø§Øµ ÙŠÙ‚ÙˆÙ…ÙˆÙ† Ø¨Ø§Ù„ØªØºØ±ÙŠØ¯ Ø¹Ù„ÙŠ ØªÙˆÙŠØªØ±Ù: Ø£ÙˆÙ„Ø¦Ùƒ Ø§Ù„Ø°ÙŠÙ† ÙŠØ­ØªØ§Ø¬ÙˆÙ† Ù„Ù…Ø²ÙŠØ¯ Ù…Ù† Ø§Ù„Ù…ØªØ§Ø¨Ø¹ÙŠÙ†&hellip;', 'div[class=\"post-details\"]', '2021-05-01 01:06:46', 'https://www.mklat.com/%d9%83%d9%8a%d9%81-%d8%aa%d8%b2%d9%8a%d8%af-%d9%85%d9%86-%d8%b4%d8%b9%d8%a8%d9%8a%d8%aa%d9%83-%d8%b9%d9%84%d9%8a-%d9%85%d9%88%d9%82%d8%b9-%d8%aa%d9%88%d9%8a%d8%aa%d8%b1-%d8%9f/', 'mklat'),
(247, 1, 'ÙƒÙŠÙ ØªØ´ØªØ±ÙŠ Ø¬Ù‡Ø§Ø²  ÙƒÙ…Ø¨ÙŠÙˆØªØ±', 'Â  Ø£ÙƒØ¨Ø± Ø®Ø·Ø£ Ù‚Ø¯ ÙŠÙ‚Ø¹ ÙÙŠÙ‡ Ù…Ù† ÙŠØ±ÙŠØ¯ Ø´Ø±Ø§Ø¡ ÙƒÙ…Ø¨ÙŠÙˆØªØ± Ø¬Ø¯ÙŠØ¯ Ø£Ù†Ù‡ Ù„Ø§ ÙŠØ­Ø¯Ø¯ Ø§Ù„Ù‡Ø¯Ù Ù…Ù†Ù‡ ØŒ Ù„Ø°Ù„Ùƒ Ø¹Ù„ÙŠÙƒ Ø§Ù†&hellip;', 'div[class=\"post-details\"]', '2021-05-01 01:06:46', 'https://www.mklat.com/%d9%83%d9%8a%d9%81-%d8%aa%d8%b4%d8%aa%d8%b1%d9%8a-%d8%ac%d9%87%d8%a7%d8%b2-%d9%83%d9%85%d8%a8%d9%8a%d9%88%d8%aa%d8%b1/', 'mklat'),
(248, 1, 'Ø§Ù„ØªÙ„ÙØ²ÙŠÙˆÙ† Ø§Ù„Ø°ÙƒÙ€ÙŠ &#8221; SMART TV &#8220;', '&nbsp; Ø§Ù„ÙƒØ«ÙŠØ± Ù…Ù† Ø§Ù„Ø´Ø±ÙƒØ§Øª Ø§Ù„Ù…ØµÙ†Ø¹Ø© Ù„Ù„ØªÙ„ÙØ²ÙŠÙˆÙ† Ø¹Ù…Ù„Øª Ø¹Ù„Ù‰ Ø§Ù†ØªØ§Ø¬ Ø£Ø¬Ù‡Ø²Ø© Ø§Ù„ØªÙ„ÙØ§Ø² Ø§Ù„Ø°ÙƒÙŠØ©. ÙˆØ¹Ù„Ù‰ Ø§Ù„Ø±ØºÙ… Ù…Ù† Ø£Ù†Ù‡Ø§ ØªØ®ØªÙ„Ù ÙÙ‚Ø· ÙÙŠ Ø¨Ø¹Ø¶&hellip;', 'div[class=\"post-details\"]', '2021-05-01 01:06:46', 'https://www.mklat.com/%d8%a7%d9%84%d8%aa%d9%84%d9%81%d8%b2%d9%8a%d9%88%d9%86-%d8%a7%d9%84%d8%b0%d9%83%d9%80%d9%8a-smart-tv/', 'mklat'),
(249, 1, 'ÙƒÙŠÙ ØªØ³ØªØ®Ø¯Ù… &#8220;Ø§Ù„Ø¢ÙŠØ¨Ø§Ø¯&#8221; Ø¨Ø¯ÙˆÙ† Ø¥Ù†ØªØ±Ù†Øª ØŸ', 'Ø±Ø¨Ù…Ø§ ØªÙˆØ§Ø¬Ù‡Ùƒ ØµØ¹ÙˆØ¨Ø§Øª ÙÙŠ ØªÙˆØµÙŠÙ„ Ø§Ù„Ø¥Ù†ØªØ±Ù†Øª Ø¥Ù„ÙŠ Ø¬Ù‡Ø§Ø² &#8220;Ø§Ù„Ø¢ÙŠØ¨Ø§Ø¯&#8221; Ø§Ù„Ø®Ø§Øµ Ø¨Ùƒ Ù„Ø¹Ù„ Ø£Ù‡Ù…Ù‡Ø§ Ø§Ù„ØªÙƒÙ„ÙØ© Ø§Ù„Ù…Ø§Ø¯ÙŠØ© ØŒ ÙˆÙ„Ù„ÙˆÙ‡Ù„Ø© Ø§Ù„Ø£ÙˆÙ„ÙŠ ØªØ¹ØªÙ‚Ø¯ Ø£Ù†Ù‡&hellip;', 'div[class=\"post-details\"]', '2021-05-01 01:06:46', 'https://www.mklat.com/%d9%83%d9%8a%d9%81-%d8%aa%d8%b3%d8%aa%d8%ae%d8%af%d9%85-%d8%a7%d9%84%d8%a2%d9%8a%d8%a8%d8%a7%d8%af-%d8%a8%d8%af%d9%88%d9%86-%d8%a5%d9%86%d8%aa%d8%b1%d9%86%d8%aa-%d8%9f/', 'mklat'),
(250, 1, 'Ø·Ø±Ù‚ Ø³Ù‡Ù„Ù‡ Ù„Ø¥Ø·Ø§Ù„Ø© Ø¹Ù…Ø± Ø¬Ù‡Ø§Ø² Ø§Ù„ÙƒÙ…Ø¨ÙŠÙˆØªØ± Ø§Ù„Ø®Ø§Øµ Ø¨Ùƒ', 'Ø·Ø±Ù‚ Ø³Ù‡Ù„Ù‡ Ù„Ø£Ø·Ø§Ù„Ù‡ Ø¹Ù…Ø± Ø¬Ù‡Ø§Ø² Ø§Ù„ÙƒÙ…Ø¨ÙŠÙˆØªØ± Ø§Ù„Ø®Ø§Øµ Ø¨Ùƒ Ù…Ø«Ù„ Ø¬Ø³Ù…Ùƒ ÙˆØ³ÙŠØ§Ø±ØªÙƒ ÙØ§Ø¬Ù‡Ø²Ù‡ Ø§Ù„ÙƒÙ…Ø¨ÙŠÙˆØªØ± Ø§Ù„Ø®Ø§ØµÙ‡ Ø¨Ùƒ ØªØ­ØªØ§Ø¬ Ù„ØªÙ†Ø¸ÙŠÙ Ù…Ù†ØªØ¸Ù… Ù„Ù„Ø­ÙØ§Ø¸ Ø¹Ù„Ù‰&hellip;', 'div[class=\"post-details\"]', '2021-05-01 01:06:46', 'https://www.mklat.com/%d8%b7%d8%b1%d9%82-%d8%b3%d9%87%d9%84%d9%87-%d9%84%d8%a5%d8%b7%d8%a7%d9%84%d8%a9-%d8%b9%d9%85%d8%b1-%d8%ac%d9%87%d8%a7%d8%b2-%d8%a7%d9%84%d9%83%d9%85%d8%a8%d9%8a%d9%88%d8%aa%d8%b1-%d8%a7%d9%84%d8%ae/', 'mklat'),
(251, 1, 'ÙƒÙŠÙÙŠÙ‡ ÙˆÙ‚Ø§ÙŠÙ‡ Ø§Ù„ÙƒÙ…Ø¨ÙŠÙˆØªØ± Ø§Ù„Ø®Ø§Øµ Ø¨Ùƒ Ù…Ù† Ø§Ù„ÙÙŠØ±ÙˆØ³Ø§Øª', 'ÙƒÙŠÙ ØªØ¹Ø±Ù Ø£Ù† Ù‡Ù†Ø§Ùƒ ÙÙŠØ±ÙˆØ³ Ø¹Ù„Ù‰ Ø§Ù„ÙƒÙ…Ø¨ÙŠÙˆØªØ± Ø§Ù„Ø®Ø§Øµ Ø¨Ùƒ Ø¹Ù†Ø¯Ù…Ø§ ÙŠÙƒÙˆÙ† Ø§Ù„ÙƒØ¨ÙŠÙˆØªØ± Ù‡Ùˆ Ø£Ø¨Ø·Ø£ Ù…Ù† Ø§Ù„Ù…Ø¹ØªØ§Ø¯ Ø¨Ø´ÙƒÙ„ Ù…Ø«ÙŠØ± Ù„Ù„Ø±ÙŠØ¨Ù‡ ,&hellip;', 'div[class=\"post-details\"]', '2021-05-01 01:06:46', 'https://www.mklat.com/%d9%83%d9%8a%d9%81%d9%8a%d9%87-%d9%88%d9%82%d8%a7%d9%8a%d9%87-%d8%a7%d9%84%d9%83%d9%85%d8%a8%d9%8a%d9%88%d8%aa%d8%b1-%d8%a7%d9%84%d8%ae%d8%a7%d8%b5-%d8%a8%d9%83-%d9%85%d9%86-%d8%a7%d9%84%d9%81%d9%8a/', 'mklat'),
(252, 1, 'ÙƒÙŠÙ ÙŠÙ…ÙƒÙ†Ùƒ ØªÙ‚Ø¨Ù„ Ø£Ù† Ø§Ù„ÙƒÙ…Ø¨ÙŠÙˆØªØ± Ø§Ù„Ø®Ø§Øµ Ø¨Ùƒ Ø¨Ø·Ø¦ ! !', 'Ù‡Ù„ Ù„Ø¯ÙŠÙƒ dsl Ø£Ù†ØªØµØ§Ù„ Ø¹Ù† Ø·Ø±ÙŠÙ‚ Ø§Ù„Ø£Ù†ØªØ±Ù†Øª ÙˆÙ„ÙƒÙ† Ù„ÙŠØ³ Ù„Ø¯ÙŠÙƒ ÙˆÙ‚Øª ÙˆØµØ¨Ø± Ù„Ø£Ù† Ø¬Ù‡Ø§Ø²Ùƒ Ø¨Ø·Ø¦ Ø¬Ø¯Ø§ , Ø¯Ø§Ø¦Ù…Ø§ Ù…Ø§ ØªØ±ÙŠØ¯&hellip;', 'div[class=\"post-details\"]', '2021-05-01 01:06:46', 'https://www.mklat.com/slow-pc/', 'mklat'),
(253, 1, 'Ø§Ù„Ø¬Ø±ÙŠÙ…Ù‡ Ø§Ù„Ø§Ù„ÙƒØªØ±ÙˆÙ†ÙŠÙ‡ ( Ø§Ù„Ø¬Ø²Ø¡ Ø§Ù„Ø§ÙˆÙ„ )', 'Ø§Ù‡ØªÙ… Ø¹Ù„Ù…Ø§Ø¡ Ø§Ù„Ø§Ø¬ØªÙ…Ø§Ø¹ Ø¨Ø¯Ø±Ø§Ø³Ø© Ø§Ù„Ø¬Ø§Ù†Ø¨ Ø§Ù„Ø§Ø¬ØªÙ…Ø§Ø¹Ù‰ Ù„Ù„Ø¬Ø±ÙŠÙ…Ù‡ Ø§Ù„Ø§Ù„ÙƒØªØ±ÙˆÙ†ÙŠÙ‡ Ø¹Ø¨Ø± Ø§Ù„Ø§Ù†ØªØ±Ù†Øª ,Ø­ÙŠØ« Ø³Ø§Ø¹Ø¯Øª ØªÙƒÙ†ÙˆÙ„ÙˆØ¬ÙŠØ§ Ø§Ù„Ù…Ø¹Ù„ÙˆÙ…Ø§Øª ÙˆÙˆØ³Ø§Ø¦Ù„ Ø§Ù„Ø§ØªØµØ§Ù„ Ø§Ù„ØªÙƒÙ†ÙˆÙ„ÙˆØ¬Ù‰ Ø¹Ù„Ù‰ Ø§Ù†ØªØ´Ø§Ø± Ø§Ù†Ù…Ø§Ø·&hellip;', 'div[class=\"post-details\"]', '2021-05-01 01:06:46', 'https://www.mklat.com/electronic-crimes/', 'mklat'),
(254, 1, 'Ø§Ù„ØªÙƒÙ†ÙˆÙ„ÙˆØ¬ÙŠØ§', 'Ø§Ù„ØªÙƒÙ†ÙˆÙ„ÙˆØ¬ÙŠØ§ .. ÙƒÙ„Ù…Ø© ØªØ´ÙŠØ± Ø¥Ù„Ù‰ Ø¹Ù…Ù„ØŒ ÙˆØªØ¹Ø¯ÙŠÙ„ØŒ ÙˆØ§Ø³ØªØ®Ø¯Ø§Ù…ØŒ ÙˆÙ…Ø¹Ø±ÙØ© Ø§Ù„Ø£Ø¯ÙˆØ§Øª ÙˆØ§Ù„Ø¢Ù„Ø§Øª ÙˆØ§Ù„ØªÙ‚Ù†ÙŠØ§ØªØŒ ÙˆØ§Ù„Ø­Ø±ÙØŒ ÙˆÙ†Ø¸Ù…ØŒ ÙˆØ£Ø³Ø§Ù„ÙŠØ¨ Ø§Ù„ØªÙ†Ø¸ÙŠÙ…ØŒ Ù…Ù† Ø£Ø¬Ù„ Ø­Ù„ Ù…Ø´ÙƒÙ„Ø©ØŒ&hellip;', 'div[class=\"post-details\"]', '2021-05-01 01:06:46', 'https://www.mklat.com/technology-defination/', 'mklat'),
(255, 2, 'â€œI&#8217;ll See You on Zoom!&#8221; International Educators&#8217; Perceptions of Online Teaching ', 'Abstract When the COVID-19 pandemic swept the world in 2020, it affected every aspect of life, including education. The spread of this pandemic compelled the world to shift from traditional classroom education to online learning. This exploratory qualitative research study investigates the critical and timely topic of the sudden transition &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:06:59', 'https://www.arabmediasociety.com/ill-see-you-on-zoom-international-educators-perceptions-of-online-teaching-amid-and-beyond-covid-19/', 'arabmediasociety'),
(256, 2, 'Impact of US Drama Binge-Watching in the Emirates: Third-Person Effect and Cultural Self-Conceptual', 'Abstract The study investigates respondentsâ€™ perception of the negative effects of US drama binge-watching on their cultural values as compared with its perceived effects on the cultural values of others. The study helps in understanding the extent to which Arab residents in the United Arab Emirates (UAE) perceive mediaâ€™s imperialist &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:06:59', 'https://www.arabmediasociety.com/impact-of-us-drama-binge-watching-in-the-emirates-third-person-effect-and-cultural-self-conceptual/', 'arabmediasociety'),
(257, 2, 'COVID-19 Pandemic and Diffusion of Fake News through Social Media in the Arab World', 'Abstract Social media platforms are among the most widely used sources of information in the world. During the COVID-19 Pandemic, the public needs access to timely and reliable information about the disease symptoms and their prevention. Thus, this study aims to determine the respondentsâ€™ perception of their trust level in &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/covid-19-pandemic-and-diffusion-of-fake-news-through-social-media-in-the-arab-world/', 'arabmediasociety'),
(258, 2, 'Sahar Khamis on Shifting Tides for Arabs and Muslims in the US', 'In light of the changes taking place in the United States, Arab Media &amp; Society asked Dr. Sahar Khamis her thoughts on how the Arab and Muslim communities in the US have been affected.Â  1) What was the most notable effect of Trumpâ€™s policies on the Muslim community in the &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/sahar-khamis-on-shifting-tides-for-arabs-and-muslims-in-the-us/', 'arabmediasociety'),
(259, 2, 'Trump, Twitter, and Regulation of Big Tech: Perspectives from the Arab World', 'The suspension of the Twitter account of former U.S. president Donald Trump after violating the platformâ€™s publishing policies brought forth significant controversy and aroused many questions about the right to freedom of expression and its boundaries, not only in the United States, but across the globe. In the Arab region, &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/trump-twitter-and-regulation-of-big-tech-perspectives-from-the-arab-world/', 'arabmediasociety'),
(260, 2, 'ØªØ£Ø«ÙŠØ± Ø§Ø³ØªØ®Ø¯Ø§Ù… Ù…ÙˆØ§Ù‚Ø¹ Ø§Ù„ØªÙˆØ§ØµÙ„ Ø§Ù„Ø§Ø¬ØªÙ…Ø§Ø¹ÙŠ Ø¹Ù„Ù‰ Ø±Ø£Ø³ Ø§Ù„Ù…Ø§Ù„ Ø§Ù„', 'Scroll down for English abstract. Ù…Ø¹ Ø§ØªØ³Ø§Ø¹ Ø¯Ø§Ø¦Ø±Ø© Ø´Ø¨ÙƒØ§Øª Ø§Ù„ØªÙˆØ§ØµÙ„ Ø§Ù„Ø§Ø¬ØªÙ…Ø§Ø¹ÙŠ ÙˆØ¬Ù…Ù‡ÙˆØ±Ù‡ ÙÙŠ Ø¯ÙˆÙ„Ø© Ø§Ù„Ø¥Ù…Ø§Ø±Ø§ØªØŒ ÙˆØªØ²Ø§ÙŠØ¯ Ø§Ù„Ø·Ù…ÙˆØ­ Ù„ØªÙˆØ¸ÙŠÙ ÙˆØ³Ø§Ø¦Ù„ Ø§Ù„ØªÙˆØ§ØµÙ„ Ø§Ù„Ø§Ø¬ØªÙ…Ø§Ø¹ÙŠ ÙÙŠ ØªØ­Ù‚ÙŠÙ‚ Ø§Ù„Ø´Ø±Ø§ÙƒØ© Ø§Ù„Ù…Ø¬ØªÙ…Ø¹ÙŠØ© ÙˆØ§Ù„ØªÙ†Ù…ÙŠØ© Ø§Ù„Ù…Ø³ØªØ¯Ø§Ù…Ø©ØŒ ÙˆØ®Ù„Ù‚ ØªØ¬Ø§Ù†Ø³ ÙˆØ§Ù†Ø¯Ù…Ø§Ø¬ ÙÙŠ Ø§Ù„Ù…Ø¬ØªÙ…Ø¹ Ø§Ù„Ø¥Ù…Ø§Ø±Ø§ØªÙŠØ› Ø£Ù‚Ø¯Ù…Øª Ø¯ÙˆÙ„Ø© Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª Ø¹Ù„Ù‰ ØªÙˆÙÙŠØ± Ø¨ÙŠØ¦Ø© Ø§Ø¬ØªÙ…Ø§Ø¹ÙŠØ© Ù„Ù„Ù…Ù‚ÙŠÙ…ÙŠÙ† ÙÙŠÙ‡Ø§ØŒ ØªØ­Ø±Øµ ÙÙŠÙ‡Ø§ Ø¹Ù„Ù‰ Ø§Ù„ØªÙˆØ§ØµÙ„ Ù…Ø¹ Ø§Ù„Ù…Ù‚ÙŠÙ…ÙŠÙ† Ù…Ù† Ø®Ù„Ø§Ù„ &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/%d8%aa%d8%a3%d8%ab%d9%8a%d8%b1-%d8%a7%d8%b3%d8%aa%d8%ae%d8%af%d8%a7%d9%85-%d9%85%d9%88%d8%a7%d9%82%d8%b9-%d8%a7%d9%84%d8%aa%d9%88%d8%a7%d8%b5%d9%84-%d8%a7%d9%84%d8%a7%d8%ac%d8%aa%d9%85%d8%a7%d8%b9/', 'arabmediasociety'),
(261, 2, 'The Development of British Public Diplomacy in the Arab World', 'Abstract This paper attempts to map the major changes and developments of British public diplomacy in the Arab world. I argue here that the BBC and the British Council have greatly assisted British public diplomacy efforts and can be regarded as effective because exerting influence in an indirect way can &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/the-development-of-british-public-diplomacy-in-the-arab-world/', 'arabmediasociety'),
(262, 2, 'Journalism and Media Education in Times of Conflict: Three Cases from the Arab Region', 'Abstract This paper examines the journalism and media education programs in three countries in the Arab region (Libya, Syria, Yemen) that have been or are still in the throes of civil wars and/or polarization along conflicting political ideologies and control of different geographical zones. Based on an online questionnaire distributed &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/journalism-and-media-education-in-times-of-conflict-three-cases-from-the-arab-region/', 'arabmediasociety'),
(263, 2, 'Precedented History: Arab Media Coverage of the Israeli â€“ UAE â€“ Bahrain Normalization Agreement', 'On September 16, 2020, U.S. president Donald Trump hosted the signing ceremony for the tripartite diplomatic normalization agreement, known as the Abraham Accords, between the United Arab Emirates (UAE), Bahrain, and Israel at the White House. The UAE is the third Arab country to declare normalization with Israel after Egypt &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/precedented-history-arab-media-coverage-of-the-israeli-uae-bahrain-normalization-agreement/', 'arabmediasociety'),
(264, 2, 'Ø¢ÙŠØ§ ØµÙˆÙÙŠØ§: Ù‚Ø±Ø§Ø¡Ø© ÙˆØªØ­Ù„ÙŠÙ„ Ù„Ù„Ø­Ø¬Ø§Ø¬ Ø§Ù„Ø¥Ø¹Ù„Ø§Ù…ÙŠ ÙˆØ§Ù„Ø¯ÙŠÙ†ÙŠ', 'Scroll down for English abstract. Ù‚Ø±Ø±Øª Ø§Ù„Ù…Ø­ÙƒÙ…Ø© Ø§Ù„Ø¥Ø¯Ø§Ø±ÙŠØ© Ø§Ù„Ø¹Ù„ÙŠØ§ Ø§Ù„ØªØ±ÙƒÙŠØ© ÙŠÙˆÙ… 10 Ù…Ù† ØªÙ…ÙˆØ²/ÙŠÙˆÙ„ÙŠÙˆ 2020 ØªØ­ÙˆÙŠÙ„ÙŽ Ù…ØªØ­Ù \"Ø¢ÙŠØ§ ØµÙˆÙÙŠØ§\" Ø¥Ù„Ù‰ Ù…Ø³Ø¬Ø¯ Ø§Ø¹ØªØ¨Ø§Ø±Ø§ Ù…Ù† ÙŠÙˆÙ… 24 Ù…Ù† Ø§Ù„Ø´Ù‡Ø± Ø°Ø§ØªÙ‡ØŒ ÙØ§Ø´ØªØ¯ Ø§Ù„Ø¬Ø¯Ù„ Ø¥Ø¹Ù„Ø§Ù…ÙŠØ§ Ø¨ÙŠÙ† Ø§Ù„ØªØ£ÙŠÙŠØ¯ ÙˆØ§Ù„Ù…Ø¹Ø§Ø±Ø¶Ø©Ø› Ø¹Ù„Ù…Ø§ Ø¨Ø£Ù† Ø§Ù„Ù…Ø¹Ø§Ø±Ø¶Ø© Ù„Ù… ØªÙ‚ØªØµØ± Ø¹Ù„Ù‰ ØºÙŠØ± Ø§Ù„Ù…Ø³Ù„Ù…ÙŠÙ†ØŒ Ø¨Ù„ Ø£Ø¹Ø±Ø¨ Ù…Ø³Ù„Ù…ÙˆÙ† ÙƒÙØ«Ø±â€“ Ø£ÙØ±Ø§Ø¯Ø§ ÙˆÙ…Ø¤Ø³Ø³Ø§Øªâ€“ Ø¹Ù† Ø±ÙØ¶Ù‡Ù… &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/%d8%a2%d9%8a%d8%a7-%d8%b5%d9%88%d9%81%d9%8a%d8%a7-%d9%82%d8%b1%d8%a7%d8%a1%d8%a9-%d9%88%d8%aa%d8%ad%d9%84%d9%8a%d9%84-%d9%84%d9%84%d8%ad%d8%ac%d8%a7%d8%ac-%d8%a7%d9%84%d8%a5%d8%b9%d9%84%d8%a7%d9%85/', 'arabmediasociety'),
(265, 2, 'Ø§Ù„Ø¨ÙŠØ¦Ø© Ø§Ù„Ø¥Ø¨Ø¯Ø§Ø¹ÙŠØ© Ù„ØµÙ†Ø§Ø¹Ø© Ø§Ù„Ù…Ø­ØªÙˆÙ‰ Ø§Ù„Ø¹Ù„Ù…ÙŠ Ø¹Ù„Ù‰ Ø§Ù„Ø´Ø¨ÙƒØ§Øª Ø§Ù„Ø', 'Scroll down for English abstract. Ù…Ù„Ø®Øµ Ø§Ù„Ø¯Ø±Ø§Ø³Ø© ÙØ±Ø¶Øª Ø§Ù„Ø´Ø¨ÙƒØ§Øª Ø§Ù„Ø§Ø¬ØªÙ…Ø§Ø¹ÙŠØ© Ù†ÙØ³Ù‡Ø§ Ø¹Ù„Ù‰ Ø£Ø³Ø§Ù„ÙŠØ¨ ØµÙ†Ø§Ø¹Ø© Ø§Ù„Ù…Ø­ØªÙˆÙ‰ Ø§Ù„Ø³Ù…Ø¹Ø¨ØµØ±ÙŠ Ø³ÙˆØ§Ø¡ Ù…Ù† Ø­ÙŠØ« Ø§Ù„ØªÙ‚Ù†ÙŠØ§Øª Ø£Ùˆ Ø·Ø¨ÙŠØ¹Ø© Ø§Ù„Ø¥Ù†ØªØ§Ø¬ ÙˆØ§Ù„Ø§Ø³ØªÙ‡Ù„Ø§ÙƒØŒ ÙˆÙ‚Ø¯ Ù…Ø«Ù„Øª Ù…Ø³Ø§Ø­Ø© Ù…Ù† Ø§Ù„Ù…ÙØªØ±Ø¶ Ø£Ù† ØªÙƒÙˆÙ† Ø­Ø±Ø© ÙˆÙ…ØªÙ‚Ø¯Ù…Ø© ÙˆÙ‚Ù„ÙŠÙ„Ø© Ø§Ù„ØªÙƒØ§Ù„ÙŠÙ Ø¨Ù…Ø§ ÙŠØ³Ù…Ø­ Ù„Ù„Ù…Ø³ØªØ®Ø¯Ù… Ø§Ù„Ù…Ù‡ØªÙ… Ø¨Ù†ÙˆØ¹ Ù…Ø­Ø¯Ø¯ Ù…Ù† Ø§Ù„Ù…Ø­ØªÙˆÙ‰ Ø£Ù† ÙŠÙ…Ø§Ø±Ø³ Ø´ÙƒÙ„Ø§Ù‹ Ù…Ø§ Ù…Ù† Ø£Ø´ÙƒØ§Ù„ Ø§Ù„Ø¥Ø¨Ø¯Ø§Ø¹ &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/%d8%a7%d9%84%d8%a8%d9%8a%d8%a6%d8%a9-%d8%a7%d9%84%d8%a5%d8%a8%d8%af%d8%a7%d8%b9%d9%8a%d8%a9-%d9%84%d8%b5%d9%86%d8%a7%d8%b9%d8%a9-%d8%a7%d9%84%d9%85%d8%ad%d8%aa%d9%88%d9%89-%d8%a7%d9%84%d8%b9%d9%84/', 'arabmediasociety'),
(266, 2, 'A Critical Analysis of the Dialectic Science-Religion Relationship in Popular Science Show Discourse', 'Abstract In light of the advancing digital environment and the interest in boosting scientific content published on digital platforms, this paper seeks to define and critically analyze the discourse of popular science shows (henceforth, â€œPSSâ€). Considering the fact that religion serves as a major foundational component in the Arab social &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/a-critical-analysis-of-the-dialectic-science-religion-relationship-in-popular-science-show-discourse/', 'arabmediasociety'),
(267, 2, 'Ø§Ù„ØªØ­ÙˆÙ„Ø§Øª ÙˆØ§Ù„Ø§ØªØ¬Ø§Ù‡Ø§Øª Ø§Ù„Ø­Ø§Ù„ÙŠØ© ÙÙŠ Ø§Ù„ØµØ­Ø§ÙØ© Ø§Ù„Ø¹Ù„Ù…ÙŠØ© ÙƒÙ…Ø§ ØªØ±Ø', 'Scroll down for English abstract. Ù…Ù„Ø®Øµ Ø§Ù„Ø¯Ø±Ø§Ø³Ø© ÙØ±Ø¶Øª Ø§Ù„Ø´Ø¨ÙƒØ§Øª Ø§Ù„Ø§Ø¬ØªÙ…Ø§Ø¹ÙŠØ© Ù†ÙØ³Ù‡Ø§ Ø¹Ù„Ù‰ Ø£Ø³Ø§Ù„ÙŠØ¨ ØµÙ†Ø§Ø¹Ø© Ø§Ù„Ù…Ø­ØªÙˆÙ‰ Ø§Ù„Ø³Ù…Ø¹Ø¨ØµØ±ÙŠ Ø³ÙˆØ§Ø¡ Ù…Ù† Ø­ÙŠØ« Ø§Ù„ØªÙ‚Ù†ÙŠØ§Øª Ø£Ùˆ Ø·Ø¨ÙŠØ¹Ø© Ø§Ù„Ø¥Ù†ØªØ§Ø¬ ÙˆØ§Ù„Ø§Ø³ØªÙ‡Ù„Ø§ÙƒØŒ ÙˆÙ‚Ø¯ Ù…Ø«Ù„Øª Ù…Ø³Ø§Ø­Ø© Ù…Ù† Ø§Ù„Ù…ÙØªØ±Ø¶ Ø£Ù† ØªÙƒÙˆÙ† Ø­Ø±Ø© ÙˆÙ…ØªÙ‚Ø¯Ù…Ø© ÙˆÙ‚Ù„ÙŠÙ„Ø© Ø§Ù„ØªÙƒØ§Ù„ÙŠÙ Ø¨Ù…Ø§ ÙŠØ³Ù…Ø­ Ù„Ù„Ù…Ø³ØªØ®Ø¯Ù… Ø§Ù„Ù…Ù‡ØªÙ… Ø¨Ù†ÙˆØ¹ Ù…Ø­Ø¯Ø¯ Ù…Ù† Ø§Ù„Ù…Ø­ØªÙˆÙ‰ Ø£Ù† ÙŠÙ…Ø§Ø±Ø³ Ø´ÙƒÙ„Ø§Ù‹ Ù…Ø§ Ù…Ù† Ø£Ø´ÙƒØ§Ù„ Ø§Ù„Ø¥Ø¨Ø¯Ø§Ø¹ &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/%d8%a7%d9%84%d8%aa%d8%ad%d9%88%d9%84%d8%a7%d8%aa-%d9%88%d8%a7%d9%84%d8%a7%d8%aa%d8%ac%d8%a7%d9%87%d8%a7%d8%aa-%d8%a7%d9%84%d8%ad%d8%a7%d9%84%d9%8a%d8%a9-%d9%81%d9%8a-%d8%a7%d9%84%d8%b5%d8%ad%d8%a7/', 'arabmediasociety'),
(268, 2, 'More than Meets the Eye: A Multimodal Approach to Science-Popularizing Discourse and Representation ', 'Abstract National Geographic Magazine (NGM) is an American cultural icon renowned for the dissemination of geographic knowledge, the exhilaration of cultural explorations, the popularization of science discourse, and the cultivation of visual imaginaries. Among popular science magazines, its distinctive force in the popular imagination squarely lies in the manipulation and &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/more-than-meets-the-eye-a-multimodal-approach-to-science-popularizing-discourse-and-representation-of-the-other-in-a-selection-of-national-geographic-feature-articles/', 'arabmediasociety'),
(269, 2, 'Applying the Four Models of Science Journalism to the Publics&#8217; Interaction with Coronavirus Ne', 'Abstract Since the outbreak of coronavirus, also known as COVID-19, the news has been covering its rapid developments by the minute, while feeding the eager publics the information they seek regarding its origin, health-threats, symptoms, preventative measures, and global impact. It is thus of pressing importance, to track the Egyptian &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/applying-the-four-models-of-science-journalism-to-the-publics-interaction-with-coronavirus-news-in-egypt/', 'arabmediasociety'),
(270, 2, 'The Earth Turns and the World has Changed: Egyptian and Arab Science Journalism in the Digital Age', 'Abstract Science journalism in Egypt reflects the way science is taught, perceived and practiced in the country. Online publications cover science and technology in different ways. Yet, all of them rely on translators as most of the science stories are sourced from foreign outlets. This paper looks at how science &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/the-earth-turns-and-the-world-has-changed-egyptian-and-arab-science-journalism-in-the-digital-age/', 'arabmediasociety'),
(271, 2, 'Film Review | Watching â€œUsâ€ in the Middle East', 'â€œUs,â€ Jordan Peeleâ€™s newly released horror film, raises questions about American identity that will appear very different to viewers outside the United States. Peele has claimed that â€œUsâ€ aims to hold up a mirror to American society, showing â€œusâ€ how â€œwe are our worst enemies.â€ But for international viewers, especially &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/film-review-watching-us-in-the-middle-east/', 'arabmediasociety'),
(272, 2, 'Marathon TV Watching among Emiratis in the Interactive Media Environment', 'Abstract The study investigates the habits of binge TV watchingâ€”also called marathon TV watchingâ€”among a sample of Emiratis. It refers to watching consecutive episodes of a series in one setting for several hours. The research examines the expected outcomes for binge-watching and the possibilities of anticipating regret after such activity, &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/marathon-tv-watching-among-emiratis-in-the-interactive-media-environment/', 'arabmediasociety'),
(273, 2, 'Ø§Ù„Ù‡ÙˆÙŠØ© Ø§Ù„Ø«Ù‚Ø§ÙÙŠØ© Ø§Ù„Ù…ÙØ¹Ù„Ù†Ø© Ø¹Ø¨Ø± Ø§Ù„Ù…Ù†ØµØ§Øª Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠØ© Ù„Ù…Ø¤Ø³', 'Scroll down for English abstract. Ø£ØµØ¨Ø­ Ø§Ù„ØªÙ†ÙˆØ¹ Ø§Ù„Ø«Ù‚Ø§ÙÙŠ Ø¸Ø§Ù‡Ø±Ø© ØªÙ…ÙŠØ² Ø¹Ø¯Ø¯ ÙƒØ¨ÙŠØ± Ù…Ù† Ø§Ù„Ù…Ø¬ØªÙ…Ø¹Ø§Øª ÙÙŠ Ø¹Ø§Ù„Ù… Ø§Ù„ÙŠÙˆÙ…ØŒ ÙˆØ§Ø²Ø¯Ø§Ø¯Øª Ø­Ø§Ø¬Ø© Â Ø§Ù„Ù…Ø¤Ø³Ø³Ø§Øª Ø¹Ø§Ø¨Ø±Ø© Ø§Ù„Ø«Ù‚Ø§ÙØ§Øª Ø¥Ù„Ù‰ ØªÙ‚Ø¯ÙŠÙ… Ù‚ÙŠÙ…Ù‡Ø§ ÙˆÙ…Ù„Ø§Ù…Ø­ Ù‡ÙˆÙŠØªÙ‡Ø§ Ø§Ù„Ø«Ù‚Ø§ÙÙŠØ© ÙÙŠ Ø¸Ù„ Ø£Ù†Ø¸Ù…Ø© ØªØ´Ø±ÙŠØ¹ÙŠØ© ÙˆØ£Ø®Ù„Ø§Ù‚ÙŠØ© Ù…ØªØ¨Ø§ÙŠÙ†Ø©ØŒ ÙˆØªÙˆØ§Ø¬Ù‡ Ù…Ø¤Ø³Ø³Ø§Øª Ø§Ù„ØªØ¹Ù„ÙŠÙ… Ø§Ù„Ø¹Ø§Ù„ÙŠ Ø§Ù„Ø¹Ø§Ù…Ù„Ø© Ø¹Ù„Ù‰ Ù†Ø·Ø§Ù‚ Ø¯ÙˆÙ„ÙŠ ØªØ­Ø¯ÙŠØ§Ù‹ ÙƒØ¨ÙŠØ±Ø§Ù‹ ÙŠØªØ¹Ù„Ù‚ Ø¨ØªØ·Ø¨ÙŠÙ‚ Ù…ÙØ±Ø¯Ø§Øª Ù‡ÙˆÙŠØªÙ‡Ø§ Ø§Ù„Ø«Ù‚Ø§ÙÙŠØ©ØŒ Ù…Ø¹ &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/%d8%a7%d9%84%d9%87%d9%88%d9%8a%d8%a9-%d8%a7%d9%84%d8%ab%d9%82%d8%a7%d9%81%d9%8a%d8%a9-%d8%a7%d9%84%d9%85%d9%8f%d8%b9%d9%84%d9%86%d8%a9-%d8%b9%d8%a8%d8%b1-%d8%a7%d9%84%d9%85%d9%86%d8%b5%d8%a7%d8%aa/', 'arabmediasociety'),
(274, 2, 'Ø®Ø·Ø§Ø¨ Ø§Ù„Ù‡ÙˆÙŠØ© Ø§Ù„Ø¯ÙŠÙ†ÙŠØ© ÙÙŠ Ø§Ù„ØµØ­Ù Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠØ© Ø§Ù„Ù…ØµØ±ÙŠØ© ÙÙŠ Ø¥Ø·', 'Scroll down for English abstract. ØªÙ‡Ø¯Ù Ø§Ù„Ø¯Ø±Ø§Ø³Ø© Ø¥Ù„Ù‰ ØªØ­Ø¯ÙŠØ¯ Ø³Ù…Ø§Øª Ø®Ø·Ø§Ø¨ Ø§Ù„Ù‡ÙˆÙŠØ© Ø§Ù„Ø¯ÙŠÙ†ÙŠØ© ÙÙŠ Ø§Ù„ØµØ­Ù Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠØ© Ø§Ù„Ù…ØµØ±ÙŠØ© ÙÙŠ Ø¥Ø·Ø§Ø± Ø§Ù„Ø­Ø±Ø¨ Ø¹Ù„Ù‰ Ø§Ù„Ø¥Ø±Ù‡Ø§Ø¨ØŒ ÙˆØ§Ù„Ø¹ÙˆØ§Ù…Ù„ ÙˆØ§Ù„Ù…ØªØºÙŠØ±Ø§Øª Ø§Ù„ØªÙŠ ØªØ´ÙƒÙ„ Ø£Ø²Ù…Ø© Ø§Ù„Ù‡ÙˆÙŠØ© Ø§Ù„Ø¯ÙŠÙ†ÙŠØ©ØŒ ÙˆØ§Ù„ØªØµÙˆØ±Ø§Øª ÙˆØ§Ù„Ø­Ù„ÙˆÙ„ Ø§Ù„Ù…Ø·Ø±ÙˆØ­Ø© Ù„Ù„Ø®Ø±ÙˆØ¬ Ù…Ù† ØªÙ„Ùƒ Ø§Ù„Ø£Ø²Ù…Ø©. ÙˆØªØ¹ØªÙ…Ø¯ Ø§Ù„Ø¯Ø±Ø§Ø³Ø© Ø¹Ù„Ù‰ ØªÙˆØ¸ÙŠÙ Ø£Ø³Ù„ÙˆØ¨ ØªØ­Ù„ÙŠÙ„ Ø§Ù„Ø®Ø·Ø§Ø¨ Ø§Ù„Ø¯ÙŠÙ†ÙŠØŒ ÙˆØ§Ù„Ù…Ù†Ù‡Ø¬ Ø§Ù„ÙƒÙŠÙÙŠ Ø§Ù„Ù…Ù‚Ø§Ø±Ù†ØŒ ÙˆØ§Ø³ØªØ®Ø¯Ù…Øª Ø§Ù„Ø¯Ø±Ø§Ø³Ø© Ù…Ù†Ù‡Ø¬ &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/%d8%ae%d8%b7%d8%a7%d8%a8-%d8%a7%d9%84%d9%87%d9%88%d9%8a%d8%a9-%d8%a7%d9%84%d8%af%d9%8a%d9%86%d9%8a%d8%a9-%d9%81%d9%8a-%d8%a7%d9%84%d8%b5%d8%ad%d9%81-%d8%a7%d9%84%d8%a5%d9%84%d9%83%d8%aa%d8%b1%d9%88/', 'arabmediasociety'),
(275, 2, 'Ø§Ù„Ù…Ø´Ø§Ø±ÙƒØ© ÙˆØ¨Ù†Ø§Ø¡ Ø§Ù„Ù‡ÙˆÙŠØ© Ø§Ù„ÙˆØ·Ù†ÙŠØ© Ø¹Ø¨Ø± Ø§Ù„Ø¨ÙˆØ§Ø¨Ø§Øª Ø§Ù„Ø­ÙƒÙˆÙ…ÙŠØ© Ø§Ù', 'Scroll down for English abstract. ØªÙ‡Ø¯Ù Ø§Ù„Ø¯Ø±Ø§Ø³Ø© Ø¥Ù„Ù‰ Ø§Ù„ØªØ¹Ø±Ù Ø¹Ù„Ù‰ Ø·Ø¨ÙŠØ¹Ø© Ø§Ù„Ø¯ÙˆØ± Ø§Ù„Ø°ÙŠ ØªÙ‚ÙˆÙ… Ø¨Ù‡ Ø§Ù„Ø¨ÙˆØ§Ø¨Ø§Øª Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠØ© Ù„Ø­ÙƒÙˆÙ…Ø§Øª Ø§Ù„Ø¯ÙˆÙ„ Ø§Ù„Ø¹Ø±Ø¨ÙŠØ© ÙÙŠ Ø§Ù„ØªØ¹Ø¨ÙŠØ± Ø¹Ù† Ù‡ÙˆÙŠØ© Ø§Ù„Ø¯ÙˆÙ„Ø© ÙˆØ§Ù„ØªØ¹Ø±ÙŠÙ Ø¨Ù‡Ø§ØŒ Ø¥Ù„Ù‰ Ø¬Ø§Ù†Ø¨ ØªØ¹Ø²ÙŠØ² Ø§Ù„Ù…Ø´Ø§Ø±ÙƒØ© Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠØ© Ù„Ù„Ù…ÙˆØ§Ø·Ù†ÙŠÙ†. ÙˆØªØ¹ØªÙ…Ø¯ Ø§Ù„Ø¯Ø±Ø§Ø³Ø© Ø¹Ù„Ù‰ ØªØ­Ù„ÙŠÙ„ Ù…Ø­ØªÙˆÙ‰ Ø§Ù„Ø¨ÙˆØ§Ø¨Ø§Øª Ø¨Ù‡Ø¯Ù Ø±ØµØ¯ ÙˆØªØ­Ù„ÙŠÙ„ Ø·Ø¨ÙŠØ¹Ø© Ø§Ù„Ù…Ø¹Ù„ÙˆÙ…Ø§Øª ÙˆØ§Ù„Ù…Ø´Ø§Ø±ÙƒØ© Ø§Ù„Ù…ØªØ§Ø­Ø© Ø¹Ù„ÙŠÙ‡Ø§ØŒ ÙˆØ°Ù„Ùƒ Ù…Ù† Ø®Ù„Ø§Ù„ &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/%d8%a7%d9%84%d9%85%d8%b4%d8%a7%d8%b1%d9%83%d8%a9-%d9%88%d8%a8%d9%86%d8%a7%d8%a1-%d8%a7%d9%84%d9%87%d9%88%d9%8a%d8%a9-%d8%a7%d9%84%d9%88%d8%b7%d9%86%d9%8a%d8%a9-%d8%b9%d8%a8%d8%b1-%d8%a7%d9%84%d8%a8/', 'arabmediasociety'),
(276, 2, 'The Changing Identity of a Living Secular Icon: Al Mayadeenâ€™s Iconization of Jamila Bouhired', 'Abstract In December 2013, the pan-Arab TV station Al Mayadeen orchestrated a big public celebration of the former female fighter Jamila Bouhired. In this article, I analyze Al Mayadeenâ€™s celebration of Bouhired as an iconization (Khalili 2009) and investigate how the TV station uses the icon Bouhired to facilitate a &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/the-changing-identity-of-a-living-secular-icon-al-mayadeens-iconization-of-jamila-bouhired/', 'arabmediasociety'),
(277, 2, 'Nationalism and the Use of Pop Music: A Discourse Analysis of the Song â€œBoshret Kheirâ€', 'Abstract The Egyptian Arabic song, â€œBoshret Kheirâ€ or â€˜good omenâ€™, represents an example of the role of popular music in promoting populism, patriotism, and the ideology of Egyptian nationalism. Given the songâ€™s popularity, this article poses the question: what transforms an ordinary pop song into a national phenomenon? The song &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/nationalism-and-the-use-of-pop-music-a-discourse-analysis-of-the-song-boshret-kheir/', 'arabmediasociety'),
(278, 2, 'Infantilizing Arab politics: A quick reading of the viral Ramadan 2018 Zain telecom ad', 'Since 2011, the Kuwaiti telecom company Zain Group, one of the largest in the Middle East, has produced a series of popular ads broadcast annually during Ramadan. The ads are songs, usually featuring celebrities singing and dancing with children. Since 2015, the ads have become noticeably more political. In 2016, &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/5853-2/', 'arabmediasociety'),
(279, 2, 'Ø§ØªØ¬Ø§Ù‡Ø§Øª Ø§Ù„Ø´Ø¨Ø§Ø¨ Ø§Ù„Ù…ØµØ±ÙŠ Ù†Ø­Ùˆ Ø­Ø±ÙŠØ© Ø§Ù„ØªØ¹Ø¨ÙŠØ± Ø¹Ù„Ù‰ Ø´Ø¨ÙƒØ© Ø§Ù„Ø¥Ù†ØªØ±', 'Scroll down for English abstract. Ø¨Ù„Øº Ø¹Ø¯Ø¯ Ù…Ø³ØªØ®Ø¯Ù…ÙŠ \"Ø§Ù„ÙˆÙŠØ¨\" ÙÙŠ Ø§Ù„Ù…Ø¬ØªÙ…Ø¹ Ø§Ù„Ù…ØµØ±ÙŠ Ù†Ø­Ùˆ 49.23 Ù…Ù„ÙŠÙˆÙ† Ù…Ø³ØªØ®Ø¯Ù… ÙˆÙÙ‚Ø§Ù‹ Ù„Ø¥Ø­ØµØ§Ø¦ÙŠØ§Øª Ø¯ÙŠØ³Ù…Ø¨Ø± 2017Ù… Ø£ÙŠ Ø¨Ù…Ø§ ÙŠÙÙ…Ø«ÙÙ‘Ù„ Ù†Ø­Ùˆ 49.5% Ù…Ù† Ø¹Ø¯Ø¯ Ø§Ù„Ø³ÙƒØ§Ù† Ø§Ù„Ù…ÙÙ‚Ø¯Ù‘Ø± Ø¨Ù†Ø­Ùˆ 99.4 Ù…Ù„ÙŠÙˆÙ† Ù†Ø³Ù…Ø©ØŒ ÙƒÙ…Ø§ ÙŠØ¨Ù„Øº Ø¹Ø¯Ø¯ Ø§Ù„Ù…Ø´ØªØ±ÙƒÙŠÙ† ÙÙŠ Ø®Ø¯Ù…Ø§Øª Ø´Ø¨ÙƒØ© Ø§Ù„ÙÙŠØ³ Ø¨ÙˆÙƒ Ù†Ø­Ùˆ 35 Ù…Ù„ÙŠÙˆÙ† Ù…Ø´ØªØ±Ùƒ. ÙˆÙŠÙÙ…Ø«ÙÙ‘Ù„ Ø§Ù„Ø´Ø¨Ø§Ø¨ Ø§Ù„Ù‚Ø·Ø§Ø¹ Ø§Ù„Ø£ÙƒØ¨Ø± &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/%d8%a7%d8%aa%d8%ac%d8%a7%d9%87%d8%a7%d8%aa-%d8%a7%d9%84%d8%b4%d8%a8%d8%a7%d8%a8-%d8%a7%d9%84%d9%85%d8%b5%d8%b1%d9%8a-%d9%86%d8%ad%d9%88-%d8%ad%d8%b1%d9%8a%d8%a9-%d8%a7%d9%84%d8%aa%d8%b9%d8%a8%d9%8a/', 'arabmediasociety'),
(280, 2, 'Ø§ØªØ¬Ø§Ù‡Ø§Øª Ø§Ù„Ù…ØµÙˆØ±ÙŠÙ† Ø§Ù„ØµØ­ÙÙŠÙŠÙ† &#8220;Ø§Ù„Ø´Ø¨Ø§Ø¨&#8221; Ù†Ø­Ùˆ Ø¥Ø¬Ø±Ø§Ø¡Ø§Øª Ø§', 'Scroll down for English abstract. Ø´Ù‡Ø¯ Ù…ÙˆØ¶ÙˆØ¹ Ø§Ù„Ø³Ù„Ø§Ù…Ø© Ø§Ù„Ù…Ù‡Ù†ÙŠØ© Ù„Ù„ØµØ­ÙÙŠÙŠÙ† Ø§Ù‡ØªÙ…Ø§Ù…Ø§Ù‹ ÙƒØ¨ÙŠØ±Ø§Ù‹ ÙÙŠ Ø§Ù„Ø³Ù†ÙˆØ§Øª Ø§Ù„Ø£Ø®ÙŠØ±Ø©Ø› ÙˆØ°Ù„Ùƒ Ù„ÙˆØ¬ÙˆØ¯ Ø§Ù„ÙƒØ«ÙŠØ± Ù…Ù† Ø§Ù„ØµØ­ÙÙŠÙŠÙ† Ø§Ù„Ø¹Ø§Ù…Ù„ÙŠÙ† ÙÙŠ Ù…Ù†Ø§Ø·Ù‚ Ø³Ø¬Ù„Øª Ø£Ù†Ù‡Ø§ Ù…Ù†Ø§Ø·Ù‚ Ø®Ø·Ø±Ø© Ø¹Ù„Ù‰ Ø§Ù„ØµØ­ÙÙŠÙŠÙ†ØŒ ÙˆØ¹Ù„Ù‰ Ø³Ù„Ø§Ù…ØªÙ‡Ù… Ø§Ù„Ù…Ù‡Ù†ÙŠØ©ØŒ ÙˆØ§Ù„Ø¨Ø¯Ù†ÙŠØ©ØŒ ÙˆØ§Ù„Ø´Ø®ØµÙŠØ©ØŒ ÙˆÙÙŠ Ø§Ù„Ø¥Ø·Ø§Ø± Ù†ÙØ³Ù‡ Ù‚Ø§Ù…Øª Ø¨Ø¹Ø¶ Ø§Ù„Ù…Ø¤Ø³Ø³Ø§Øª Ø¨ÙˆØ¶Ø¹ Ù‚ÙˆØ§Ø¹Ø¯ Ù„Ù„Ø³Ù„Ø§Ù…Ø© Ø§Ù„Ù…Ù‡Ù†ÙŠØ© Ù„Ù„ØµØ­ÙÙŠÙŠÙ†ØŒ Ø¥Ù„Ø§ Ø£Ù† Ø§Ù„ÙƒØ«ÙŠØ± Ù…Ù†Ù‡Ù… Ù„Ù… &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/%d8%a7%d8%aa%d8%ac%d8%a7%d9%87%d8%a7%d8%aa-%d8%a7%d9%84%d9%85%d8%b5%d9%88%d8%b1%d9%8a%d9%86-%d8%a7%d9%84%d8%b5%d8%ad%d9%81%d9%8a%d9%8a%d9%86-%d8%a7%d9%84%d8%b4%d8%a8%d8%a7%d8%a8-%d9%86%d8%ad%d9%88/', 'arabmediasociety'),
(281, 2, 'Ø¯ÙˆØ± Ø´Ø¨ÙƒØ§Øª Ø§Ù„ØªÙˆØ§ØµÙ„ Ø§Ù„Ø§Ø¬ØªÙ…Ø§Ø¹ÙŠ ÙÙŠ Ø¯Ø¹Ù… Ø§Ù„Ø¹Ù…Ù„ Ø§Ù„ØªØ·ÙˆØ¹ÙŠ Ù„Ø¯Ù‰ Ø§Ù', 'Scroll down for English abstract. Ø¹Ù„Ù‰ Ø§Ù„Ø±ØºÙ… Ù…Ù† Ø£Ù‡Ù…ÙŠØ© Ø§Ù„Ø¹Ù…Ù„ Ø§Ù„ØªØ·ÙˆØ¹ÙŠ ÙÙŠ Ù…Ø³Ø§Ø±Ø§Øª Ø§Ù„ØªÙ†Ù…ÙŠØ© Ø§Ù„Ù…Ø³ØªØ¯Ø§Ù…Ø©ØŒ ÙˆÙÙ‰ Ø§Ø³ØªØ«Ù…Ø§Ø± ÙˆÙ‚Øª Ø§Ù„Ø´Ø¨Ø§Ø¨ ÙÙ‰ Ø£Ø¹Ù…Ø§Ù„ ØªØ·ÙˆØ¹ÙŠØ© Ù…ÙÙŠØ¯Ø©ØŒ ÙØ¥Ù† Ù…Ù…Ø§Ø±Ø³Ø© Ø§Ù„Ø¹Ù…Ù„ Ø§Ù„Ø§Ø¬ØªÙ…Ø§Ø¹ÙŠ Ø§Ù„ØªØ·ÙˆØ¹ÙŠ ØªØ®ØªÙ„Ù Ù…Ù† Ù…Ø¬ØªÙ…Ø¹ Ù„Ø¢Ø®Ø± ÙˆÙ…Ù† Ù…Ù†Ø·Ù‚Ø© Ù„Ø£Ø®Ø±Ù‰ØŒ ÙˆÙ…Ù† ÙˆØ³ÙŠÙ„Ø© Ø¥Ø¹Ù„Ø§Ù…ÙŠØ© Ù„Ø£Ø®Ø±Ù‰Ø› Ø­ÙŠØ« ØªØªÙ†ÙˆØ¹ ÙƒÙØ§Ø¡ØªÙ‡Ø§ ÙˆØ¯Ø±Ø¬Ø§ØªÙ‡Ø§ Ø§Ù„ØªØ£Ø«ÙŠØ±ÙŠØ© ÙÙ‰ Ø§Ù„Ø¬Ù…Ù‡ÙˆØ±Ø› ÙˆÙ…Ù† Ø«Ù… ØªØªØ¨Ù„ÙˆØ± Ù…Ø´ÙƒÙ„Ø© &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/%d8%af%d9%88%d8%b1-%d8%b4%d8%a8%d9%83%d8%a7%d8%aa-%d8%a7%d9%84%d8%aa%d9%88%d8%a7%d8%b5%d9%84-%d8%a7%d9%84%d8%a7%d8%ac%d8%aa%d9%85%d8%a7%d8%b9%d9%8a-%d9%81%d9%8a-%d8%af%d8%b9%d9%85-%d8%a7%d9%84%d8%b9/', 'arabmediasociety'),
(282, 2, 'Youth in Morocco: Rebels without a Cause? Youth Violence, Social Media, and the Discontents of Moroc', 'Abstract Recently the Moroccan public had to grapple with what was perceived to be a worrying upsurge in youth crime related to Tsharmil or (cyber) bullying in the Moroccan vernacular. Mainstream media coverage of this issue ushered in an overwhelming sense of panic towards â€œdeviantâ€ youth that pose a serious &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:00', 'https://www.arabmediasociety.com/youth-in-morocco-rebels-without-a-cause-youth-violence-social-media-and-the-discontents-of-moroccan-consumer-society/', 'arabmediasociety'),
(283, 2, 'New Media, New Audiences: Charting the Rise of Spiritual and Religious MusicÂ in Egypt', 'Abstract Music is the language that everyone understands. As an element of culture, music evolved with the development of civilizations. Some of the religious subgroups produced a unique type of music that echoed in the Arabian Peninsula as well as nearby civilizations, such as Andalusia and Persia. This type of &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:01', 'https://www.arabmediasociety.com/new-media-new-audiences-charting-the-rise-of-spiritual-and-religious-music-in-egypt/', 'arabmediasociety'),
(284, 2, 'Al Hayat Daily Adrift in a Sea of Media Sharks', 'It was the go-to pan-Arab newspaper that noted journalists, analysts, and anyone worth their salt wrote for, and that readers seeking professional reporting and deconstructing of events picked up for balanced coverage, diverse views, and hard-hitting editorialsâ€”all relatively speaking, of course. Quite a tall order for a daily in a &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:01', 'https://www.arabmediasociety.com/al-hayat-daily-adrift-in-a-sea-of-media-sharks/', 'arabmediasociety'),
(285, 2, '&#8220;Football Isn&#8217;t For Arabs&#8221;: A World Cup Defeat That Resonated across the Arab Worl', 'Sitting in aÂ Cairo cafe in a crowded mall surrounded by crowds of people I watch Egyptian fans cheering for their favourite team to win theÂ World Cup final match as if cheering for their own nation. The majority were rooting for the Croatian teamâ€”a fact that wasÂ very obvious from where I &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:01', 'https://www.arabmediasociety.com/lions-of-atlas-eagles-of-carthage-green-falcons-and-the-pharaohs-a-world-cup-defeat-that-resonated-across-the-arab-world/', 'arabmediasociety'),
(286, 2, 'Filling in the Blanks: New book dives into the tragedy and complexity of post-Gadhafi Libya', 'Since the uprisings that spread across the Arab region took hold in Libya in 2011 and forced the removal of longtime ruler Muammar al-Gadhafi, the countryâ€™s fortunes have spiraled downwards. Despite an unsustainable system of governance, Gadhafiâ€™s harsh rule had maintained relative stability in a country with a history of &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:01', 'https://www.arabmediasociety.com/filling-in-the-blanks-new-book-dives-into-the-tragedy-and-complexity-of-post-gadhafi-libya/', 'arabmediasociety'),
(287, 2, 'The Ambassador: Mohamed Salah and the Future of Xenophobia in Football', 'While a post-Brexit United Kingdom continues to struggle with xenophobia and anxieties about the Arab/Muslim diaspora, a new hero has emerged in the countryâ€™s most popular sport. Heâ€™s wildly talented, heâ€™s from Egypt, and heâ€™s Muslim. Known as â€œThe Pharaohâ€, â€œThe Egyptian Kingâ€, and even the â€œEgyptian Messiâ€, 25-year-old Mohamed &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:01', 'https://www.arabmediasociety.com/the-ambassador-mohamed-salah-and-the-future-of-xenophobia-in-football/', 'arabmediasociety'),
(288, 2, 'Ø¯ÙˆØ± Ø§Ù„Ø¥Ø¹Ù„Ø§Ù… Ù‚Ø¨Ù„ ÙˆØ£Ø«Ù†Ø§Ø¡ ÙˆØ¨Ø¹Ø¯ Ø§Ù„Ø£Ø²Ù…Ø§Øª ÙˆØ§Ù„ØµØ±Ø§Ø¹Ø§Øª Ø§Ù„Ù…Ø³Ù„Ø­Ø©', 'ØªÙ‚Ø¯Ù… ØªÙ„Ùƒ Ø§Ù„ÙˆØ±Ù‚Ø© ØªØ£ØµÙŠÙ„Ø§Ù‹ Ù†Ø¸Ø±ÙŠØ§Ù‹ Ù„Ø¹Ù„Ø§Ù‚Ø© Ø§Ù„Ø¥Ø¹Ù„Ø§Ù… Ø¨Ø§Ù„Ø£Ø²Ù…Ø§Øª Ù…Ù† Ø®Ù„Ø§Ù„ Ø·Ø±Ø­ Ù…Ø¬Ù…ÙˆØ¹Ø© Ù…Ù† Ø§Ù„Ù…Ø­Ø§ÙˆØ± Ø§Ù„ØªÙŠ ØªØ³Ø§Ù‡Ù… ÙÙŠ ØªÙˆØ¶ÙŠØ­ Ù…Ø±Ø§Ø­Ù„ Ø§Ù„Ø£Ø²Ù…Ø© ÙˆØ¯ÙˆØ± Ø§Ù„Ø¥Ø¹Ù„Ø§Ù… ÙÙŠ ÙƒÙ„ Ù…Ø±Ø­Ù„Ø© Ù…Ù† Ù…Ø±Ø§Ø­Ù„Ù‡Ø§ØŒ ÙˆØ°Ù„Ùƒ Ø¨ØºÙŠØ© ØªÙ‚Ø¯ÙŠÙ… Ø±Ø¤ÙŠØ© ØªØ¯ÙØ¹ Ù†Ø­Ùˆ Ø§Ù„ØªØ¹Ø§Ù…Ù„ Ø¨Ø´ÙƒÙ„ Ø£ÙØ¶Ù„ Ù…Ø¹ Ø§Ù„Ø£Ø²Ù…Ø§ØªØŒ ÙˆÙ‚Ø¯ Ø¬Ø§Ø¡Øª ØªÙ„Ùƒ Ø§Ù„Ù…Ø­Ø§ÙˆØ± ÙƒÙ…Ø§ ÙŠØ£ØªÙŠ: Ø¯ÙˆØ±Ø© Ø­ÙŠØ§Ø© Ø§Ù„Ø£Ø²Ù…Ø© The Crisis Life &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:01', 'https://www.arabmediasociety.com/%d8%af%d9%88%d8%b1-%d8%a7%d9%84%d8%a5%d8%b9%d9%84%d8%a7%d9%85-%d9%82%d8%a8%d9%84-%d9%88%d8%a3%d8%ab%d9%86%d8%a7%d8%a1-%d9%88%d8%a8%d8%b9%d8%af-%d8%a7%d9%84%d8%a3%d8%b2%d9%85%d8%a7%d8%aa/', 'arabmediasociety'),
(289, 2, 'Ø¯ÙˆØ± Ø§Ù„ØµØ­Ø§ÙØ© Ø§Ù„Ø¨Ù†Ø§Ø¡Ø© ÙˆÙ‚Øª Ø§Ù„Ø£Ø²Ù…Ø§Øª', 'ØªÙ…Ù‡ÙŠØ¯: ØªØªÙ†Ø§ÙˆÙ„ Ù‡Ø°Ù‡ Ø§Ù„ÙˆØ±Ù‚Ø© Ø¯ÙˆØ± Ø§Ù„ØµØ­Ø§ÙØ© Ø§Ù„Ø¨Ù†Ø§Ø¡Ø© ÙˆÙ‚Øª Ø§Ù„Ø£Ø²Ù…Ø§ØªØŒ Ø®Ø§ØµØ© ÙÙŠ Ø§Ù„Ø¯ÙŠÙ…Ù‚Ø±Ø§Ø·ÙŠØ§Øª Ø§Ù„Ø§Ù†ØªÙ‚Ø§Ù„ÙŠØ©ØŒ ÙˆØªÙ‡ØªÙ… Ø¨ØªØ¹Ø±ÙŠÙ Ù…ØµØ·Ù„Ø­ Ø§Ù„ØµØ­Ø§ÙØ© Ø§Ù„Ø¨Ù†Ø§Ø¡Ø© ÙˆØ£Ù‡Ù…ÙŠØªÙ‡Ø§ ÙÙŠ Ø§Ù„Ù…Ø±Ø­Ù„Ø© Ø§Ù„Ø§Ù†ØªÙ‚Ø§Ù„ÙŠØ© Ø§Ù„Ø­Ø§Ù„ÙŠØ©ØŒ Ø®Ø§ØµØ© ÙÙŠ Ù…ÙˆØ§Ø¬Ù‡Ø© Ø§Ù„Ø£Ø²Ù…Ø§Øª. Ø­ÙŠØ« ØªØ²Ø¯Ø§Ø¯ Ø£Ù‡Ù…ÙŠØ© ÙˆØ³Ø§Ø¦Ù„ Ø§Ù„Ø¥Ø¹Ù„Ø§Ù… ÙˆÙŠÙ‚Ø¹ Ø¹Ù„Ù‰ Ø¹Ø§ØªÙ‚Ù‡Ø§ Ø¯ÙˆØ± ÙƒØ¨ÙŠØ± ÙˆÙ‚Øª Ø§Ù„Ø£Ø²Ù…Ø§ØªØ› Ù„Ù…Ø§ Ù„Ù‡Ø§ Ù…Ù† Ù‚Ø¯Ø±Ø§Øª Ù‡Ø§Ø¦Ù„Ø© Ø¹Ù„Ù‰ Ø§Ù„ØªØ£Ø«ÙŠØ± ÙÙŠ Ø³Ù„ÙˆÙƒÙŠØ§Øª Ø§Ù„Ø¬Ù…Ù‡ÙˆØ±Ù¬ ÙˆÙ„Ù…Ø§ &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:01', 'https://www.arabmediasociety.com/%d8%af%d9%88%d8%b1-%d8%a7%d9%84%d8%b5%d8%ad%d8%a7%d9%81%d8%a9-%d8%a7%d9%84%d8%a8%d9%86%d8%a7%d8%a1%d8%a9-%d9%88%d9%82%d8%aa-%d8%a7%d9%84%d8%a3%d8%b2%d9%85%d8%a7%d8%aa/', 'arabmediasociety'),
(290, 2, 'Social Media Applications in Crisis Management of Natural Disasters: Lessons for the Arab Region', 'Introduction Throughout history, nations have suffered natural disasters that inflict damage, spread chaos, and claim lives. In contrast to anthropogenic or human-made disasters that are usually limited in scope, a natural disaster can impact a whole country, or even a continent. Earthquakes, volcanoes, floods, landslides, and hurricanes, to name a &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:01', 'https://www.arabmediasociety.com/social-media-applications-in-crisis-management-of-natural-disasters-lessons-for-the-arab-region/', 'arabmediasociety'),
(291, 2, 'Shining New Light on the Palestinian Cause: The Unintended Consequences of Trumpâ€™s Jerusalem Decla', 'A few days before U.S. President Donald Trump declared that America would recognize Jerusalem as the capital of Israel, a number of Arab heads Â of stateâ€”including the leaders of Jordan, Saudi Arabia, and the Palestinian Authority (not yet a state but one in the making since Oslo)â€”wereÂ  informed that Trump &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:01', 'https://www.arabmediasociety.com/shining-new-light-on-the-palestinian-cause-the-unintended-consequences-of-trumps-jerusalem-declaration/', 'arabmediasociety'),
(292, 2, 'BOOK REVIEW | As Terrorism Evolves', 'Seib, P. (2017). As Terrorism Evolves: Media, Religion and Governance. Cambridge, U.K.: Cambridge University Press. USC journalism professor Philip Seib has done a great service for those who follow media-driven events connected with terrorism inspired by Middle East- and Africa-based terror groups that have, for many, become household names, such &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:01', 'https://www.arabmediasociety.com/book-review-as-terrorism-evolves/', 'arabmediasociety'),
(293, 2, 'Local Media Framing of Egyptian Monetary Policy: Insights from the 2016 Flotation of the Pound', 'Abstract On November 3, 2016, the Central Bank of Egypt (CBE) announced the free flotation of the Egyptian pound in an attempt to stabilize the economy. Following this announcement, the CBE issued a series of press releases addressing the matter, and the flotation was widely covered by local media. This &hellip;', 'article[class=\"item-list\"]', '2021-05-01 01:07:01', 'https://www.arabmediasociety.com/local-media-framing-of-egyptian-monetary-policy-insights-from-the-2016-flotation-of-the-pound/', 'arabmediasociety');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `email` varchar(50) NOT NULL,
  `pass` varchar(50) NOT NULL,
  `name` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `email`, `pass`, `name`) VALUES
(52, 'androkhaled7@gmail.com', '111', 'donandrooo');

-- --------------------------------------------------------

--
-- Table structure for table `websites`
--

CREATE TABLE `websites` (
  `id` int(11) NOT NULL,
  `namez` varchar(200) NOT NULL,
  `link` varchar(20000) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `websites`
--

INSERT INTO `websites` (`id`, `namez`, `link`, `created_at`) VALUES
(1, 'mklat', 'https://www.mklat.com/category/technology/computer-internet/', '2021-04-30 21:36:12'),
(2, 'arabmediasociety', 'https://www.arabmediasociety.com/category/features/', '2021-04-30 21:36:12');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `articles`
--
ALTER TABLE `articles`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `websites`
--
ALTER TABLE `websites`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `articles`
--
ALTER TABLE `articles`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=294;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=53;

--
-- AUTO_INCREMENT for table `websites`
--
ALTER TABLE `websites`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
